#!/usr/bin/env bash
#
# Run all dotfiles installers.
# Stolen from https://github.com/holman/dotfiles/blob/master/script/install, thanks 😘

set -e

# gitconfig
echo "🍰  updating gitconfig..."
mkdir -p ~/.git-scripts/hooks
cp ./git/.gitconfig ~/.gitconfig
cp ./git/squash.sh ~/.git-scripts/squash.sh
cp ./git/copy-untracked.sh ~/.git-scripts/copy-untracked.sh
cp ./git/hooks/* ~/.git-scripts/hooks/
git config --global credential.helper osxkeychain

# find the installers and run them iteratively
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

for src in $(find -H . -maxdepth 4 -name install.sh | sed 's|/[^/]*$||')
do
  (
  file=`realpath $src`
  echo "⛑  installing $file..."
  cd $file
  sh install.sh
  echo "   done!"
  )
done

echo "🍰  getting xcode dev tools..."
if ! xcode-select -p; then
  xcode-select --install
fi
