#!/usr/bin/env bash

set -e

# zsh
echo "🎁  zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "Setup me dev places"
mkdir -p dev

# nvm
echo "🎁  nvm..."
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | sudo bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

echo "⛑  setting up node..."
nvm install --lts
nvm use --lts

echo "⛑  updating npm to the latest and greatest..."
sudo npm -g install npm@latest

# run npm things
echo "⛑  npm installing some stuff..."
npm install -g diff-so-fancy

echo "⛑  update brew"
brew update

echo "⛑  installing yarn"
brew install yarn

echo "⛑  installing python"
brew install pyenv pyenv-virtualenv

echo "⛑  log in to the npm repo"
echo "⚠️ ⚠️ 👇 you will need to enter your staffId credentials"
npm login --registry=https://npm-private.atlassian.io --scope=atlassian

echo "⛑  install micros-cli"
brew tap atlassian/micros ssh://git@stash.atlassian.com:7997/micros/micros-cli-homebrew-tap.git
brew install micros-cli

echo "Go go gadget"
brew install go
brew install dep

mkdir -p ~/dev/go/src

